---
version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cfncheck/*.yaml
  y-lint:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: pip install yamllint
      - run:
          name: Run yamllint
          command: yamllint yamlcheck/*.yml
workflows:
  raisetech:
    jobs:
      - cfn-lint
      - y-lint
